const GET_ALL_INGREDIENTS: 'GET_ALL_INGREDIENTS' = 'GET_ALL_INGREDIENTS';
const GET_ALL_INGREDIENTS_SUCCESS: 'GET_ALL_INGREDIENTS_SUCCESS'  = 'GET_ALL_INGREDIENTS_SUCCESS';
const GET_ALL_INGREDIENTS_FAILED: 'GET_ALL_INGREDIENTS_FAILED' = 'GET_ALL_INGREDIENTS_FAILED';

const REORDER_INGREDIENT: 'REORDER_INGREDIENT' = 'REORDER_INGREDIENT';
const ADD_TO_CONSTRUCTOR: 'ADD_TO_CONSTRUCTOR' = 'ADD_TO_CONSTRUCTOR';
const DELETE_FROM_CONSTRUCTOR: 'DELETE_FROM_CONSTRUCTOR' = 'DELETE_FROM_CONSTRUCTOR';

const GET_CURRENT_INGREDIENT: 'GET_CURRENT_INGREDIENT' = 'GET_CURRENT_INGREDIENT';
const GET_CURRENT_INGREDIENT_SUCCESS: 'GET_CURRENT_INGREDIENT_SUCCESS' = 'GET_CURRENT_INGREDIENT_SUCCESS';
const GET_CURRENT_INGREDIENT_FAILED: 'GET_CURRENT_INGREDIENT_FAILED' = 'GET_CURRENT_INGREDIENT_FAILED';

const LOGIN: 'LOGIN' = 'LOGIN';
const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

const LOGOUT: 'LOGOUT' = 'LOGOUT';
const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

const GET_ORDER: 'GET_ORDER' = 'GET_ORDER';
const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
const CLOSE_ORDER: 'CLOSE_ORDER' = 'CLOSE_ORDER';

const RECOVER_PASSWORD: 'RECOVER_PASSWORD' = 'RECOVER_PASSWORD';
const RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS' = 'RECOVER_PASSWORD_SUCCESS';
const RECOVER_PASSWORD_FAILED: 'RECOVER_PASSWORD_FAILED' = 'RECOVER_PASSWORD_FAILED';

const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD';
const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';

const REGISTER: 'REGISTER' = 'REGISTER';
const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

const GET_USER: 'GET_USER' = 'GET_USER';
const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';

const EDIT_USER: 'EDIT_USER' = 'EDIT_USER';
const EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS' = 'EDIT_USER_SUCCESS';
const EDIT_USER_FAILED: 'EDIT_USER_FAILED' = 'EDIT_USER_FAILED';



export {GET_ALL_INGREDIENTS, GET_ALL_INGREDIENTS_SUCCESS, GET_ALL_INGREDIENTS_FAILED,
  ADD_TO_CONSTRUCTOR, DELETE_FROM_CONSTRUCTOR, REORDER_INGREDIENT,
  GET_CURRENT_INGREDIENT, GET_CURRENT_INGREDIENT_SUCCESS, GET_CURRENT_INGREDIENT_FAILED,
  LOGIN, LOGIN_SUCCESS, LOGIN_FAILED,
  LOGOUT, LOGOUT_SUCCESS, LOGOUT_FAILED,
  GET_ORDER, GET_ORDER_SUCCESS, GET_ORDER_FAILED, CLOSE_ORDER,
  RESET_PASSWORD, RESET_PASSWORD_SUCCESS, RESET_PASSWORD_FAILED,
  RECOVER_PASSWORD, RECOVER_PASSWORD_SUCCESS, RECOVER_PASSWORD_FAILED,
  REFRESH_TOKEN, REFRESH_TOKEN_SUCCESS, REFRESH_TOKEN_FAILED,
  REGISTER, REGISTER_SUCCESS, REGISTER_FAILED,
  GET_USER, GET_USER_SUCCESS, GET_USER_FAILED, EDIT_USER, EDIT_USER_SUCCESS, EDIT_USER_FAILED
};
